name: Bug Report
description: Report a reproducible defect in PMC.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps, payloads, and headers.
      placeholder: |
        1. Call endpoint ...
        2. Observe ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, and PMC version/commit.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and Evidence
      description: Include sanitized logs and request IDs.

