name: Feature Request
description: Suggest a new capability for PMC.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Which integration or business pain does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: API/events/config impact and rollout plan.
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: Backward Compatibility
      description: Explain if the change is additive or breaking.
    validations:
      required: true

